In [106]:
import numpy as np
import pandas as pd

# import scipy
# from scipy.linalg import null_space, svd
import scipy
import scipy.linalg


In [118]:
import httpx

async def request(year: int):
    URL = f"https://api.collegefootballdata.com:443/games?year={year}&seasonType=regular"

    authorization = "Bearer NJRgktQC/FilkL37+s4ZSvckBKL/Iox5fw18DumOF+X8u2DntZqcJ44P9imkoG+t"

    headers = {
        "Authorization": authorization,
        "X-Requested-With": "https://peyton.creery.org/",
    }

    # response = await app.state.client.get(URL, headers=headers)
    # print(response)

    scores = {}
    async with httpx.AsyncClient() as client:
        resp = await client.get(URL, headers=headers)
        scores = resp.json()
        
        allowed_divisions = ['fbs', 'fcs', 'ii']
        scores = [game for game in scores if (game["home_division"] in allowed_divisions) and (game["away_division"] in allowed_divisions)]

    return {"scores": scores}


In [108]:


def null_space(A, rcond=None):
    """
    Construct an orthonormal basis for the null space of A using SVD

    Parameters
    ----------
    A : (M, N) array_like
        Input array
    rcond : float, optional
        Relative condition number. Singular values ``s`` smaller than
        ``rcond * max(s)`` are considered zero.
        Default: floating point eps * max(M,N).

    Returns
    -------
    Z : (N, K) ndarray
        Orthonormal basis for the null space of A.
        K = dimension of effective null space, as determined by rcond

    See Also
    --------
    svd : Singular value decomposition of a matrix
    orth : Matrix range

    Examples
    --------
    1-D null space:

    >>> import numpy as np
    >>> from scipy.linalg import null_space
    >>> A = np.array([[1, 1], [1, 1]])
    >>> ns = null_space(A)
    >>> ns * np.copysign(1, ns[0,0])  # Remove the sign ambiguity of the vector
    array([[ 0.70710678],
           [-0.70710678]])

    2-D null space:

    >>> from numpy.random import default_rng
    >>> rng = default_rng()
    >>> B = rng.random((3, 5))
    >>> Z = null_space(B)
    >>> Z.shape
    (5, 2)
    >>> np.allclose(B.dot(Z), 0)
    True

    The basis vectors are orthonormal (up to rounding error):

    >>> Z.T.dot(Z)
    array([[  1.00000000e+00,   6.92087741e-17],
           [  6.92087741e-17,   1.00000000e+00]])

    """
    u, s, vh = scipy.linalg.svd(A, full_matrices=True)

    display(pd.DataFrame(s))
    # show last 10 singular values
    display(pd.DataFrame(s[-10:]))

    M, N = u.shape[0], vh.shape[1]
    if rcond is None:
        rcond = np.finfo(s.dtype).eps * max(M, N)
    tol = np.amax(s, initial=0.) * rcond
    num = np.sum(s > tol, dtype=int)
    Q = vh[num:,:].T.conj()
    return Q


def null_space2(A, rcond=None):
    u, s, vh = scipy.linalg.svd(A, full_matrices=True)
    M, N = u.shape[0], vh.shape[1]
    if rcond is None:
        rcond = np.finfo(s.dtype).eps * max(M, N)
    tol = np.amax(s) * rcond
    num = np.sum(s > tol, dtype=int)
    Q = vh[num:,:].T.conj()
    return Q


In [109]:

def compute_ranking(M):
    # Sum of the columns in 1D matrix
    col_sum = np.sum(M, axis=0)
    # Subtract games matrix with diagonal matrix of column sum
    diff = M - np.diag(col_sum)
    # compute null-space matrix of the difference
    ranking_matrix = null_space(diff)
    # Take the absolute value of the array
    ranking_matrix = np.absolute(ranking_matrix)
    # print("ranking matrix", ranking_matrix)

    # # Quick-fix for when null_space returns a matrix size of (x,>1) instead of expected (x,1)
    # if ranking_matrix.shape[1] != 1:
    #     # print("uh oh, no bueno")
    #     new_ranking_matrix = np.array([])
    #     for row in ranking_matrix:
    #         best_cell = 0
    #         # print(row)
    #         for cell in row:
    #             if cell > best_cell:
    #                 best_cell = cell
    #         new_value = np.array([best_cell])
    #         # print(new_value)
    #         new_ranking_matrix = np.append(
    #             new_ranking_matrix, new_value, axis=0
    #         )
    #     # print("new matrix", len(new_ranking_matrix), new_ranking_matrix)
    #     ranking_matrix = new_ranking_matrix

    print(ranking_matrix.shape)
    print(ranking_matrix)
    if ranking_matrix.shape[1] != 1:
        # just get the last column
        ranking_matrix = ranking_matrix[:, -1]


    # Convert to a python List
    ranking = ranking_matrix.flatten().tolist()
    return ranking


def weird_division(n, d):
    return n / d if d else 0


In [119]:
scores = await request(2024)
# display(scores)
data = scores["scores"]
# display(data)
# print unique home_divisions
home_divisions = set([game["home_division"] for game in data])
display(home_divisions)

# filter out games that are home_division != None
# allowed_divisions = ['fbs', 'fcs', 'ii']
# data = [game for game in data if (game["home_division"] in allowed_divisions) and (game["away_division"] in allowed_divisions)]
display(data)

{'fbs', 'fcs', 'ii'}

[{'id': 401635525,
  'season': 2024,
  'week': 1,
  'season_type': 'regular',
  'start_date': '2024-08-24T16:00:00.000Z',
  'start_time_tbd': False,
  'completed': True,
  'neutral_site': True,
  'conference_game': True,
  'attendance': None,
  'venue_id': 3504,
  'venue': 'Aviva Stadium',
  'home_id': 59,
  'home_team': 'Georgia Tech',
  'home_conference': 'ACC',
  'home_division': 'fbs',
  'home_points': 24,
  'home_line_scores': [7, 7, 0, 10],
  'home_post_win_prob': '0.9913955304658811',
  'home_pregame_elo': 1497,
  'home_postgame_elo': 1513,
  'away_id': 52,
  'away_team': 'Florida State',
  'away_conference': 'ACC',
  'away_division': 'fbs',
  'away_points': 21,
  'away_line_scores': [8, 6, 0, 7],
  'away_post_win_prob': '0.008604469534118864',
  'away_pregame_elo': 1692,
  'away_postgame_elo': 1676,
  'excitement_index': '7.8222239620',
  'highlights': None,
  'notes': 'Aer Lingus College Football Classic'},
 {'id': 401654665,
  'season': 2024,
  'week': 1,
  'season_type': 're

In [117]:
teams = []
for game in data:
    if game["home_team"] not in teams:
        teams.append(game["home_team"])

    if game["away_team"] not in teams:
        teams.append(game["away_team"])

# print number of teams
print("Team count:", len(teams))

# Generate game matrix
M_offense = np.zeros((len(teams), len(teams)), dtype=int)
for game in data:
    i = teams.index(game["home_team"])
    j = teams.index(game["away_team"])
    M_offense[i, j] = (
        game["home_points"] if game["home_points"] != None else 0
    )
    M_offense[j, i] = (
        game["away_points"] if game["away_points"] != None else 0
    )
M_defense = np.transpose(M_offense)

M_defense_df = pd.DataFrame(M_defense)
# add team names to the dataframe first row an column
M_defense_df.columns = teams
M_defense_df.index = teams

# export M_defense_df to csv
M_defense_df.to_csv("defense_matrix.csv")

display(M_defense_df)

rank_offense = compute_ranking(M_offense)
rank_defense = compute_ranking(M_defense)
ranking = [weird_division(i, j) for i, j in zip(rank_offense, rank_defense)]

# Create dict and combine values of teams and ranking
# ranking_dict = {}
# print(ranking)
# for i, rank in enumerate(ranking):
#     ranking_dict[teams[i]] = rank

# Create array of teams and ranking
ranking_dict = [
    {"team": team, "rating": rank} for team, rank in zip(teams, ranking)
]

# Sort the array by rating
ranking_dict = sorted(ranking_dict, key=lambda k: k["rating"], reverse=True)
# add rank to the dict
for i, team in enumerate(ranking_dict):
    team["rank"] = i + 1

display(ranking_dict)
# return ranking_dict


Team count: 427


Georgia Tech  Florida State  Tarleton State  McNeese  \
Georgia Tech               0             21               0        0   
Florida State             24              0               0        0   
Tarleton State             0              0               0       23   
McNeese                    0              0              26        0   
New Mexico                 0              0               0        0   
...                      ...            ...             ...      ...   
Cornell                    0              0               0        0   
Anderson (Sc)              0              0               0        0   
Roosevelt                  0              0               0        0   
Yale                       0              0               0        0   
Pennsylvania               0              0               0        0   

                New Mexico  Montana State  Southeast Missouri State  \
Georgia Tech             0              0                         0   
Florida State            0              0                         0   
Tarleton State           0              0                         0   
McNeese                  0              0                         0   
New Mexico               0             35                         0   
...                    ...            ...                       ...   
Cornell                  0              0                         0   
Anderson (Sc)            0              0                         0   
Roosevelt                0              0                         0   
Yale                     0              0                         0   
Pennsylvania             0              0                         0   

                North Alabama  Norfolk State  Florida A&M  ...  Columbia  \
Georgia Tech                0              0            0  ...         0   
Florida State               0              0            0  ...         0   
Tarleton State             14              0            0  ...         0   
McNeese                     0              0            0  ...         0   
New Mexico                  0              0            0  ...         0   
...                       ...            ...          ...  ...       ...   
Cornell                     0              0            0  ...         0   
Anderson (Sc)               0              0            0  ...         0   
Roosevelt                   0              0            0  ...         0   
Yale                        0              0            0  ...        13   
Pennsylvania                0              0            0  ...        23   

                Princeton  Harvard  Brown  Dartmouth  Cornell  Anderson (Sc)  \
Georgia Tech            0        0      0          0        0              0   
Florida State           0        0      0          0        0              0   
Tarleton State          0        0      0          0        0              0   
McNeese                 0        0      0          0        0              0   
New Mexico              0        0      0          0        0              0   
...                   ...      ...    ...        ...      ...            ...   
Cornell                35       38     23          0        0              0   
Anderson (Sc)           0        0      0          0        0              0   
Roosevelt               0        0      0          0        0              0   
Yale                    0        0     34         44       47              0   
Pennsylvania            0        0     28         20       49              0   

                Roosevelt  Yale  Pennsylvania  
Georgia Tech            0     0             0  
Florida State           0     0             0  
Tarleton State          0     0             0  
McNeese                 0     0             0  
New Mexico              0     0             0  
...                   ...   ...           ...  
Cornell                 0    23            67  
Anderson (Sc)           0     0         

0
0    5.243342e+02
1    5.181624e+02
2    5.126969e+02
3    5.050780e+02
4    4.962263e+02
..            ...
422  1.198982e+01
423  5.777153e+00
424  3.687209e+00
425  1.914388e-13
426  3.250535e-15

[427 rows x 1 columns]

0
0  2.866822e+01
1  2.699270e+01
2  2.280988e+01
3  2.007357e+01
4  1.525387e+01
5  1.198982e+01
6  5.777153e+00
7  3.687209e+00
8  1.914388e-13
9  3.250535e-15

(427, 2)
[[0.00000000e+00 8.04653190e-02]
 [2.96235458e-17 3.85659826e-02]
 [3.73856774e-17 1.73650215e-02]
 [3.36578390e-17 1.85534833e-02]
 [1.80213195e-17 2.69487414e-02]
 [1.95349528e-17 4.64933603e-02]
 [4.08443582e-17 1.98751382e-02]
 [3.27049251e-18 1.30823726e-02]
 [1.15984575e-17 8.14794571e-03]
 [2.65122333e-17 1.31400324e-02]
 [2.00831770e-17 3.93816204e-02]
 [5.48870489e-17 1.04968473e-01]
 [1.03239146e-16 3.59106292e-02]
 [2.85552228e-17 7.70950746e-03]
 [1.25800155e-18 1.15141480e-03]
 [9.54731431e-18 2.20736670e-03]
 [7.61759112e-19 2.20526773e-03]
 [2.04278554e-17 6.64214590e-03]
 [4.32376009e-17 6.57228886e-02]
 [4.12344863e-17 8.25406523e-03]
 [4.25494213e-17 3.19786329e-03]
 [5.08100238e-17 1.07763141e-03]
 [4.26848956e-18 2.61958902e-02]
 [1.65735898e-17 1.49797732e-02]
 [2.33697143e-17 2.28199027e-02]
 [1.44154207e-18 1.13542011e-02]
 [2.82807452e-17 2.41136698e-02]
 [6.62461408e-19 9.83375348e-03]
 [1.62857844e-20 1.91895479e-02]
 [4.00755374e-19 6.10917922e-03]
 

0
0    5.473452e+02
1    5.108587e+02
2    4.919618e+02
3    4.903877e+02
4    4.868476e+02
..            ...
422  6.661529e+00
423  5.372334e+00
424  3.795046e+00
425  2.424286e-13
426  1.843170e-14

[427 rows x 1 columns]

0
0  2.168992e+01
1  1.880295e+01
2  1.562968e+01
3  1.198745e+01
4  7.004855e+00
5  6.661529e+00
6  5.372334e+00
7  3.795046e+00
8  2.424286e-13
9  1.843170e-14

(427, 2)
[[0.00000000e+00 3.13285941e-03]
 [2.65182947e-17 5.38569483e-03]
 [7.81857953e-17 9.83831828e-03]
 [5.00525541e-17 1.25907748e-02]
 [1.79418418e-18 8.62078961e-03]
 [2.98548780e-17 5.68763445e-03]
 [4.76152138e-17 1.03090464e-02]
 [1.02045691e-16 1.49113889e-02]
 [7.86751905e-17 2.30873895e-02]
 [1.16537235e-16 2.05231869e-02]
 [2.41754163e-18 6.48875148e-03]
 [1.22956408e-17 2.31054930e-03]
 [4.91065378e-17 7.68504029e-03]
 [5.98552464e-18 3.68175425e-02]
 [3.30084003e-17 8.52275636e-02]
 [9.24284469e-17 4.63506704e-02]
 [5.28105042e-17 9.43111008e-02]
 [1.98915865e-17 2.24738761e-02]
 [4.88804881e-17 3.72481957e-03]
 [6.31007790e-17 3.39096200e-02]
 [5.68558356e-17 4.86025669e-02]
 [6.36326129e-17 1.45448864e-01]
 [1.26262407e-16 8.59164101e-03]
 [6.71466444e-17 1.68299549e-02]
 [4.26478353e-17 8.84139557e-03]
 [9.34186530e-17 1.68721326e-02]
 [1.08358420e-17 8.11473027e-03]
 [5.20751646e-17 2.21833298e-02]
 [2.52045395e-17 1.03022928e-02]
 [4.26940681e-17 3.48471566e-02]
 

[{'team': 'Ohio State', 'rating': 344.5629464750193, 'rank': 1},
 {'team': 'Ole Miss', 'rating': 291.9026192641642, 'rank': 2},
 {'team': 'Texas', 'rating': 272.2085589152084, 'rank': 3},
 {'team': 'Alabama', 'rating': 242.47670411358303, 'rank': 4},
 {'team': 'Tennessee', 'rating': 236.89789276278805, 'rank': 5},
 {'team': 'Notre Dame', 'rating': 178.16960218679245, 'rank': 6},
 {'team': 'Georgia', 'rating': 153.76603411764646, 'rank': 7},
 {'team': 'Indiana', 'rating': 137.35016184694658, 'rank': 8},
 {'team': 'South Carolina', 'rating': 133.35028309861968, 'rank': 9},
 {'team': 'Penn State', 'rating': 129.59899005883537, 'rank': 10},
 {'team': 'Oregon', 'rating': 119.22137719566666, 'rank': 11},
 {'team': 'USC', 'rating': 69.05372914431668, 'rank': 12},
 {'team': 'Louisville', 'rating': 68.59127132266275, 'rank': 13},
 {'team': 'Miami', 'rating': 66.85931740613859, 'rank': 14},
 {'team': 'LSU', 'rating': 66.573553182802, 'rank': 15},
 {'team': 'Texas A&M', 'rating': 66.5389299136698